# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-SpaceTrack
version:      0.023
version_from: lib/Astro/SpaceTrack.pm
installdirs:  site
requires:
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
