---
name: Astro-SpaceTrack
version: 0.042
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Download satellite orbital elements from Space Track
license: perl
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Astro-SpaceTrack
  license: http://dev.perl.org/licenses/
requires:
  Compress::Zlib: 0
  HTML::Parser: 0
  HTTP::Response: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  Params::Util: 0.12
  perl: 5.006
configure_requires:
  Module::Build: 0.35
dynamic_config: 1
provides:
  Astro::SpaceTrack:
    file: lib/Astro/SpaceTrack.pm
    version: 0.042
  Astro::SpaceTrack::Parser:
    file: lib/Astro/SpaceTrack/Parser.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  directory:
    - inc
    - t
