---
name: Astro-SpaceTrack
version: 0.032
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Download satellite orbital elements from Space Track
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Compress::Zlib: 0
  HTML::Parser: 0
  HTTP::Response: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
dynamic_config: 1
provides:
  Astro::SpaceTrack:
    file: lib/Astro/SpaceTrack.pm
    version: 0.032
  Astro::SpaceTrack::Parser:
    file: lib/Astro/SpaceTrack/Parser.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
